# Generated by Django 5.0 on 2025-07-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view book'), ('can_create', 'can create book'), ('can_edit', 'can edit book'), ('can_delete', 'can delete book')]},
        ),
    ]
